name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg libcairo2-dev
#    - name: Build
#      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
